### ISSUE TITLE
sorting feature does not work.

### ISSUE THREAD

**Issue by oleksandrbyk** [jeremydaly/serverless-mysql#107]
I was just trying to run the following instruction.
```
await mysql.query(`SELECT * from log ORDER BY ? ? LIMIT ? OFFSET ?`, ['action_timestamp', 'DESC', 5, 1]);
```
It doesn't sort the logs data by action_timestamp in descending.
When I ran the following query on mysql client, it worked perfectly.(it returned the logs data descending by action_timestamp.
```
SELECT * from `log` ORDER BY action_timestamp DESC LIMIT 5 OFFSET 1`
```
Can anyone help me with the issue?

**Comment by nsundberg** [comment]
Your `mysql.query()` call is escaped to:
```sql
SELECT * from log ORDER BY 'action_timestamp' 'DESC' LIMIT 5 OFFSET 1
```
Note the single quotes around the `ORDER BY` params, this means that it will attempt to order by those static strings. That's because `?` should be used to escape values, not identifiers like column names. For identifiers you must use `??`, see https://github.com/mysqljs/mysql#escaping-query-identifiers. Assuming the column name (to order by) and the order (`ASC`/`DESC`) comes from an untrusted source I would do something like:
```js
// Untrusted variables from e.g. user input
const orderParam = 'DESC';
const orderByParam = 'action_timestamp';

const order = orderParam.toUpperCase() === 'DESC' ? 'DESC' : 'ASC';
await mysql.query(`SELECT * from log ORDER BY ?? ${order} LIMIT ? OFFSET ?`, [orderByParam, 5, 1]);
```

Which results in (note the backticks):
```sql
SELECT * from log ORDER BY `action_timestamp` DESC LIMIT 5 OFFSET 1
```
