### ISSUE TITLE
Serverless is not Working in NEXTJS

### ISSUE THREAD

**Issue by ChuyD3v** [jeremydaly/serverless-mysql#154]
during a GET Request there is an error  
Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

**Comment by rigobertoalag** [comment]
Try this:

`ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';`

Where root is your current db user and password is your current password, if you hace mysql workbench you can paste the sentence and run the code to change the native password identifier.

**Comment by naorpeled** [comment]
Hey @TheAfrvlz,
I haven't encountered such an issue myself, but based on a quick online search @rigobertoalag's solution should do the trick, otherwise it's worth trying using `mysql2` (you can do that by following the instructions in [this readme section](https://github.com/jeremydaly/serverless-mysql#consideration-when-using-typescript)).

I'll be closing this issue for now because it doesn't seem like there's something we can do on our end,
but feel free to ping me if you have additional questions/thoughts.
