### ISSUE TITLE
Clarification on the term *instances*

### ISSUE THREAD

**Issue by offero** [jeremydaly/serverless-mysql#29]
The readme states:
> ... scale almost infinitely by creating separate instances for each concurrent user

What is meant by **instances**?

**Comment by jeremydaly** [comment]
Hi @offero,

Lambda (and other FaaS offerings) scale by creating new containers for each concurrent execution. That means that if you have 500 concurrent users calling the same Lambda function, then 500 instances of your Lambda function are running, all with their own stateless environment. From a MySQL connection perspective, this means that each *instance* would need its own connection to the database.

Hope that makes sense.

- Jeremy

**Comment by offero** [comment]
Does a container mean a new node process?

**Comment by jeremydaly** [comment]
In this context, yes. Containers are actual containers (similar to Docker containers) that run your code. So the same container will get reused over and over again for *subsequent* requests, but if more than one request happens at a time, then a new container is created to handle each *concurrent* request.

See this for more details on how Lambda scales: https://docs.aws.amazon.com/lambda/latest/dg/scaling.html

**Comment by offero** [comment]
This seems like such a problem with serverless deployments. Each lambda has to connect to the database. It seems like we would want code that connects to a database to share lambda execution environments so that there are less lambdas overall that have to connect.

It's creative to ask the database itself about the connection limits, although it still seems possible to thrash on connections once you hit a certain scale. What kind of issues drove you to create this library?

**Comment by jeremydaly** [comment]
Yes and no. The serverless execution model (or FaaS specifically), was built to scale **stateless** environments. Adding state with database connections or caches adds a bottleneck unless the underlying resource can scale as well. MySQL databases (or any RDBMS for that matter) do not scale well, regardless of the connection issue. Connection pooling in traditional architectures mitigates the connection problem to some degree, but it doesn't really help to reduce pressure on the hardware since most tasks are CPU intensive. At scale, RDBMS requires all sorts of tricks like sharding and replication, which IMO, is a pain to manage and not really ideal.

If you're building a serverless application, finding a way to store data in a more scalable system is preferable, like using a NoSQL solution (e.g. DynamoDB). There are, of course, still times when RDBMS is useful (and or necessary), so until there are better scalable RDBMS solutions (Serverless Aurora is a good start), then workarounds will be necessary.

For me, I was processing data from webhooks that wrote into a MySQL database. There were bursts at times that exceeded 500 concurrent users, and we'd often get connection issues because of zombie connections from disconnected or recycled Lambda functions. I figured a fairly straightforward cleanup mechanism would solve the problem. I was actually running a variation of this for about a year before I turned it into an OSS library, so it is pretty well battle-tested.
