### ISSUE TITLE
Question: How might I be able to do an INSERT ON DUPLICATE KEY UPDATE query?

### ISSUE THREAD

**Issue by rpelletierrefocus** [jeremydaly/serverless-mysql#74]
So I have something like below to insert multiple rows of values from a json encoded body (I left some of the code out)

But what I really want to do is 

something like

let sql = "INSERT INTO  `daily_reports` (`FIPS`,`Town_County`, `Province_State`) VALUES ?
ON DUPLICATE KEY UPDATE ....."

I can't wrap my head around what to do after UPDATE

any help is greatly appreciated

```
module.exports.insert_covid_daily = async (event, context, callback) => {

    var as = JSON.parse(event.body);
    var result = [];

    for(var i in as) {
        console.log(as[i]);
        var r = [];
        for (var v in as[i]) {
            console.log(as[i][v]);
            r.push(as[i][v]);
        }
        result.push(r);
        console.log(r);
    }


    let array = result;

    context.callbackWaitsForEmptyEventLoop = false;
    let sql = "INSERT INTO  `daily_reports` (`FIPS`,`Town_County`, `Province_State`) VALUES ? ";

    const functions = await db.query(sql, [array]);
```

**Comment by christopherchubb** [comment]
```INSERT INTO  `daily_reports` 
(`FIPS`,`Town_County`, `Province_State`) 
VALUES ?
ON DUPLICATE KEY UPDATE
`Town_Country` = VALUES(`TownCountry`),
`Province_State` = COALESCE(VALUES('Province_State`), `Province_State`) -- How you do it if you don't want to lose the existing value if the update has a NULL. That may not make sense for you.```

**Comment by jeremydaly** [comment]
@rpelletierrefocus, you just need to place the update statement, e.g. `UPDATE Town_County = ?, Province_State = ?`. This is assuming that `fips` is your `PRIMARY KEY`.

**Comment by jeremydaly** [comment]
Hi @christopherchubb. If I'm interpreting your question correctly, it seems like you may be able to use `IS_NULL` as a condition check to test your incoming value, or maybe just write application logic that checks for the values existence and then builds the query accordingly.

**Comment by christopherchubb** [comment]
If you are using a parameter object with all the fields that match the table, and submitting key/value pairs that have values, then use the regular `field=VALUES(field)` syntax. That will replace each of the fields in the ON DUPLICATE KEY UPDATE with the submitted values (even if null). If you don't want to replace a field value with null, use the `field = COALESCE(VALUES(field), field)` syntax because COALESCE will choose the original field value to "replace" into the record if the submitted value (VALUES(field)) is NULL). ISNULL() is a nearly synonym for COALESCE(), except that it can cause data truncation and is not an ANSI SQL standard. I only included the COALESCE() example because it's a way to write the ON DUPLICATE KEY UPDATE part without needing to include all fields in the update. 

Of course, you could use code to modify the list of fields in the ON DUPLICATE KEY UPDATE block to match only submitted fields. I use that method too when doing PATCH updates.
